### ISSUE TITLE
about octfusion VAE results issue: not smooth compare to gt mesh

### ISSUE THREAD

**Issue by CvHadesSun** [octree-nn/octfusion#8]
Hi, a great job, i have some question about vae in this work. when i use the pretrained vae model to test vae performance, i get some results like follow, the surface is rather rough, not smooth , comparing with gt mesh. And also i train vae with my own dataset, and i get the same results, so I want to know , this issue is normal in octree-based representation in your experiments? But i find in generation results, the surface is a bit smoother.  I want to know why?

vae results:
![snapshot01](https://github.com/user-attachments/assets/4131897d-d9ea-4fa8-b1c5-8a94115fc012)
![snapshot02](https://github.com/user-attachments/assets/837c8f51-e2eb-47f1-8f45-4cf7a8bbe23d)
![snapshot03](https://github.com/user-attachments/assets/d85b3f1c-766a-4174-bbc7-fe60c3d56a63)

uncondition generation results:
![snapshot00](https://github.com/user-attachments/assets/aff70a48-d3b0-4e35-9ee5-240e8de709e5)
![snapshot01](https://github.com/user-attachments/assets/81c81a4c-1b01-4303-bb05-36c619471568)
![snapshot02](https://github.com/user-attachments/assets/29e0dbac-5ace-4e05-9994-4caac340e866)

**Comment by wst2001** [comment]
Hi, I notice that you use your own dataset, perhaps you can check the following items:
1. Have you repair mesh (using `tools/repair_mesh.py`)? Sampling point clouds on a non-watertight mesh may produce internal points, and the direction of normals might not be toward outside.
2. Before constructing octrees, the coordinate range of pointclouds should be in around [-0.8, +0.8]. `point_scale` in config can be used to adjust pointcloud range.
3. Changing a random seed might work. In our experiments, we also found that some random seeds will lead to rough surface, but most will not. That's because VAE has a sampling process.

**Comment by CvHadesSun** [comment]
Thanks  your advice: 1. yes, I sample gt label from water-tight mesh with your scripts `tools/repair_mesh.py`; 2. i just use default config `point_scale=0.5`, I' ll findout pointclouds range; 3. I'll try this advice, thank you~
